import os
import base64
import json

"""
Convert WireGuard configuration to NekoBox.
To make the final file generated by the script effective, simply copy it to NekoBox !
"""

def convert_conf_to_custom_format(conf_directory, output_path):
    # Read all .conf files in the specified directory
    wg_files = [f for f in os.listdir(conf_directory) if f.endswith('.conf')]

    # Prepare to write to the output file
    with open(output_path, 'w') as output_file:
        for filename in wg_files:
            file_path = os.path.join(conf_directory, filename)
            with open(file_path, 'r') as file:
                # Parse the .conf file content
                config_data = file.read()
                conf_lines = config_data.split('\n')
                conf_dict = {}
                for line in conf_lines:
                    if line and '=' in line:  # Check if line contains '='
                        parts = line.split('=', 1)
                        conf_dict[parts[0].strip()] = parts[1].strip()
            
                # Remove the '.conf' extension for the VPN name
                vpn_name = os.path.splitext(filename)[0]

                # Convert the content to the new JSON format
                json_format = {
                    "_v": 0,
                    "addr": "127.0.0.1",
                    "cmd": [""],
                    "core": "internal",
                    "cs": json.dumps({
                        "tag": "wg-out",
                        "type": "wireguard",
                        "interface_name": "wg0",
                        "server": conf_dict.get('Endpoint', '').split(':')[0],
                        "server_port": int(conf_dict.get('Endpoint', '0:0').split(':')[1]),
                        "local_address": [conf_dict.get('Address', '') + "/32"],
                        "peer_public_key": conf_dict.get('PublicKey', ''),
                        "private_key": conf_dict.get('PrivateKey', ''),
                        "mtu": 1420,
                        "system_interface": False
                    }, separators=(',', ':')),
                    "mapping_port": 0,
                    "name": vpn_name,
                    "port": 1080,
                    "socks_port": 0
                }

                # Convert to JSON string and Base64 encode
                json_string = json.dumps(json_format)
                base64_encoded = base64.b64encode(json_string.encode('utf-8')).decode('utf-8')
                
                # Write the nekoray custom URL to the output file
                custom_url = f"nekoray://custom#{base64_encoded}"
                output_file.write(custom_url + "\n")

    print(f"All WireGuard configurations have been converted and saved to {output_path}")

# Set the WireGuard configuration directory and output file path
wg_conf_directory = "/home/user/WireGuard/"
output_file_path = "/home/user/WireGuard/converted_configs.txt"

# Call the conversion function
convert_conf_to_custom_format(wg_conf_directory, output_file_path)
